adminer:
  image: dockerizedrupal/adminer:1.0.11
  hostname: adminer
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - adminer-data
  environment:
    - SERVER_NAME=localhost
    - TIMEZONE=Etc/UTC
    - TIMEOUT=300
    - PROTOCOLS=https,http
    - MYSQL_HOST=
    - MYSQL_PORT=3306
    - MYSQL_USERNAME=container
    - MYSQL_PASSWORD=container
    - HTTP_BASIC_AUTH_USERNAME=container
    - HTTP_BASIC_AUTH_PASSWORD=
adminer-data:
  image: dockerizedrupal/data:1.0.3
  hostname: adminer-data
  volumes:
    - /adminer
