adminer:
  image: viljaste/adminer:latest
  hostname: adminer
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - adminerdata
  environment:
    - SERVER_NAME=localhost
    - TIMEOUT=300
    - PROTOCOLS=https,http
    - USERNAME=root
    - PASSWORD=root
adminerdata:
  image: viljaste/data:latest
  hostname: adminerdata
  volumes:
    - /adminer
