adminer:
  image: dockerizedrupal/adminer:1.0.4
  hostname: adminer
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - adminer-data
  environment:
    - SERVER_NAME=localhost
    - TIMEOUT=300
    - PROTOCOLS=https,http
    - MYSQL_HOST=
    - MYSQL_PORT=3306
    - MYSQL_USERNAME=root
    - MYSQL_PASSWORD=root
adminer-data:
  image: dockerizedrupal/data:1.0.3
  hostname: adminer-data
  volumes:
    - /adminer
